### ISSUE TITLE
[BUG] Installing cc_prompt_settings kills the Cat :\

### ISSUE THREAD

**Issue by HyperUpscale** [cheshire-cat-ai/plugins#31]
When I press install the plugin to change
Cheshire Cat Prompt Settings by [Team Sviluppo](https://www.teamsviluppo.it/)

That triggers the installation for "cat/plugins/cc_prompt_settings/requirements.txt",
which tries to install langchain 0.0.279, so pip removes first langchain==0.0.336, while cheshire-cat 1.4.1 requires langchain==0.0.336.

Which effectively kills the Cat and cannot start anymore,

"ModuleNotFoundError: No module named 'langchain.embeddings.fastembed'

Is this a known issue ?

![287545568-6d1a37ab-0259-4ae5-80ac-9b69cccf99d5](https://github.com/cheshire-cat-ai/plugins/assets/126105457/d215b2b7-f19d-4e77-922d-1861c979cade)

**Comment by EugenioPetulla** [comment]
Thank you for signaling this. I will close the issue just because I've found out you reached the author. I will monitor the state o the issue on the original repo so we can decide if eliminate the plugin if no updates happens.

If you need a way to change the original prompt actually we advice you to use the C.A.T. - Cat Advanced Tools plugin that has this feature/option.
